# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Updated Graph(s)
      CI_COMMIT_AUTHOR: Github Actions - Alyx Burke
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib firebase
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      run: |
        python reader.py
    - name: Commit and Push
      run: |
        git add *
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git push -u origin gh-pages
